### PR TITLE
Fix chart app creating namespace even if exists

### LINKED ISSUE #128: Using chart "app" without namespace tries to create namespace "default"
When using `k3sup  app install chart --repo-name jetstack/cert-manager` it tries to create a namespace `default` which fails because it already exists

```sh
exec:  kubectl create namespace default
res: 
Error: kubectl exit code 1, stderr: Error from server (AlreadyExists): namespaces "default" already exists

```
## Expected Behaviour

It works and installs into the default namespace, or even if a namespace was used, if it exists it might fail, which we don't want.

## Current Behaviour

It fails because it cant create a namespace

## Possible Solution

dont return an error if the namespace exists? Or don't try and create it if it exists?

## Steps to Reproduce (for bugs)

1. create k3d cluster
2. run `k3sup  app install chart --repo-name jetstack/cert-manager`

## Your Environment

* What OS or type or VM are you using? Where is it hosted?
k3d, helm2
* Operating System and version (e.g. Linux, Windows, MacOS):
macos

### PR DESCRIPTION
**Pull request by Waterdrips**
## Description
The chart app (installs chart without tiller)
was trying too create the namespace passed in
(or default if not set) even if it existed,
this gave an error so the command failed
instead of skipping if namespace exists and installing

Signed-off-by: Alistair Hey <alistair@heyal.co.uk>

closes #128 
## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
#128 

## How Has This Been Tested?

New k3d cluster, before the fix installing like this : `k3sup app install chart --repo-name stable/nginx-ingress` failed because it tried to create the default namespace.

Now running that command ( without a namespase set) works.

Supplying a specific namespace still works too, and if that namespace already exists then it still works:
`./k3sup app install chart --repo-name stable/nginx-ingress -n this-ns` works first time

`kubectl create namespace other-ns`
`./k3sup app install chart --repo-name stable/nginx-ingress -n other-ns`

works too.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: pkg/cmd/chart_app.go [hunk 1]
```diff
@@ -91,9 +91,14 @@ before using the generic helm chart installer command.`,
 			return err
 		}
 
-		err = kubectl("create", "namespace", namespace)
+		err = kubectl("get", "namespace", namespace)
```
Comment (alexellis) [inline pkg/cmd/chart_app.go]: Shouldn't it be kubectlTask and check for non zero exit? I thought err was just for if the command didn't exist.

Comment (Waterdrips) [reply pkg/cmd/chart_app.go]: good point - changed.

File: pkg/cmd/chart_app.go [hunk 2]
```diff
@@ -91,11 +91,19 @@ before using the generic helm chart installer command.`,
...
 
-		err = kubectl("create", "namespace", namespace)
-		if err != nil {
+		res, kcErr := kubectlTask("get", "namespace", namespace)
+
+		if kcErr != nil {
 			return err
 		}
 
+		if res.ExitCode != 0 {
```
Comment (alexellis) [inline pkg/cmd/chart_app.go]: Of course, we could do:

```
kubectl create ns X --dryrun -o yaml | kubectl apply -f -
```
